# How to re-create (kubectl):
#   kubectl delete -f config-map.yaml --ignore-not-found
#   kubectl apply  -f config-map.yaml
#   kubectl get configmap config-map -o yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-map
data:
  # USER DB
  USER_DB_NAME: userdb
  USER_DB_HOST: pg-db-user
  USER_DB_PORT: "15432"
  # POSTING DB
  POSTING_DB_NAME: postingdb
  POSTING_DB_HOST: pg-db-posting
  POSTING_DB_PORT: "15433"
  # NOTIFICATION DB
  NOTIFICATION_DB_NAME: notificationdb
  NOTIFICATION_DB_HOST: pg-db-notification
  NOTIFICATION_DB_PORT: "15435"
  # MinIO (K8s)
  MINIO_ENDPOINT: http://minio-s3:9000
  MINIO_PUBLIC_ENDPOINT: http://127.0.0.1:30103
  # Public endpoint used by presigned URLs (NodePort or external LB)
  MINIO_BUCKET_IMAGES: images
  MINIO_BUCKET_VIDEOS: videos
  # File Service Endpoint (K8s)
  FILE_SERVICE_BASE_URL: http://file-service:90
  # User Service Endpoint (K8s)
  USER_SERVICE_BASE_URL: http://user-service:90
  # FILE DB
  FILE_DB_NAME: filedb
  FILE_DB_HOST: pg-db-file
  FILE_DB_PORT: "15434"
  # Kafka
  KAFKA_BOOTSTRAP_SERVERS: kafka:9990
  # OTLP Tracing Endpoint (K8s)
  OTLP_TRACING_ENDPOINT: http://tempo-otlp-http:4318/v1/traces


