# How to re-create (kubectl):
#   kubectl delete -f dev-proxy.yaml --ignore-not-found
#   kubectl apply  -f dev-proxy.yaml
#   kubectl get deploy dev-proxy
#   kubectl get svc dev-proxy
#
# Rollout / 이미지 교체 재배포:
#   # 최신 이미지로 강제 롤링 업데이트
#   kubectl rollout restart deploy/dev-proxy
#   kubectl rollout status deploy/dev-proxy
#   # 필요 시 롤백
#   kubectl rollout undo deploy/dev-proxy
#
# Quick test:
#   curl -i http://localhost:32290/user-service/test
#   curl -i http://localhost:32290/file-service/test
#   curl -i http://localhost:32290/posting-service/test
#   curl -i http://localhost:32290/notification-service/notification/test

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dev-proxy-nginx-conf
data:
  default.conf: |
    server {
      listen 80;
      server_name _;
      # allow large uploads (adjust as needed)
      client_max_body_size 200m;

      # /user-service/<anything> -> http://host.docker.internal:90/<anything>
      location ~ ^/user-service(/|$)(.*) {
        # rewrite first to avoid variables in proxy_pass (no resolver needed)
        rewrite ^/user-service(/|$)(.*) /$2 break;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://host.docker.internal:90;
      }

      location ~ ^/file-service(/|$)(.*) {
        # rewrite first to avoid variables in proxy_pass (no resolver needed)
        rewrite ^/file-service(/|$)(.*) /$2 break;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://host.docker.internal:91;
      }

      location ~ ^/posting-service(/|$)(.*) {
        # rewrite first to avoid variables in proxy_pass (no resolver needed)
        rewrite ^/posting-service(/|$)(.*) /$2 break;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_pass http://host.docker.internal:92;
      }

      location ~ ^/notification-service(/|$)(.*) {
        # rewrite first to avoid variables in proxy_pass (no resolver needed)
        rewrite ^/notification-service(/|$)(.*) /$2 break;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 600s;
        
        proxy_pass http://host.docker.internal:93;
      }

      # Add more mappings here following the same pattern
      # Example: /post-service -> host.docker.internal:18080
      # location ~ ^/post-service(/|$)(.*) {
      #   rewrite ^/post-service(/|$)(.*) /$2 break;
      #   proxy_pass http://host.docker.internal:18080;
      # }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dev-proxy
  template:
    metadata:
      labels:
        app: dev-proxy
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
      volumes:
        - name: nginx-conf
          configMap:
            name: dev-proxy-nginx-conf

---
apiVersion: v1
kind: Service
metadata:
  name: dev-proxy
spec:
  type: NodePort
  selector:
    app: dev-proxy
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 32290


