# How to re-create (kubectl):
#   kubectl delete -f file-service.yaml --ignore-not-found
#   kubectl apply  -f file-service.yaml
#   kubectl get deploy file-service && kubectl get svc file-service -o wide
# Rollout / 이미지 교체:
#   kubectl rollout restart deploy/file-service
#   kubectl rollout status deploy/file-service
#   kubectl rollout undo deploy/file-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: file-service
  template:
    metadata:
      labels:
        app: file-service
    spec:
      containers:
        - name: file-service
          image: ytkwon91/file-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 90
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: FILE_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: FILE_DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: FILE_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: FILE_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: FILE_DB_PASSWORD
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 90
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 90
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: file-service
  labels:
    app: file-service
spec:
  type: NodePort
  selector:
    app: file-service
  ports:
    - name: http
      port: 90
      targetPort: 90
      nodePort: 32091


