# How to re-create (kubectl):
#   kubectl delete -f notification-service.yaml --ignore-not-found
#   kubectl apply  -f notification-service.yaml
#   kubectl get deploy notification-service-deploy
#   kubectl get svc notification-service
#
# Rollout / 이미지 교체 재배포:
#   # 최신 이미지로 강제 롤링 업데이트
#   kubectl rollout restart deploy/notification-service-deploy
#   kubectl rollout status deploy/notification-service-deploy
#   # 필요 시 롤백
#   kubectl rollout undo deploy/notification-service-deploy

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ytkwon91/notification-service:0.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 90
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: NOTIFICATION_DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: NOTIFICATION_DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: NOTIFICATION_DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: NOTIFICATION_DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secret
                  key: NOTIFICATION_DB_PASSWORD
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: config-map
                  key: KAFKA_BOOTSTRAP_SERVERS
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 90
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 90
            initialDelaySeconds: 30
            periodSeconds: 20
            failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  type: NodePort
  selector:
    app: notification-service
  ports:
    - name: http
      port: 90
      targetPort: 90
      nodePort: 32093



