# How to re-create (kubectl):
#   kubectl delete -f redis.yaml --ignore-not-found
#   kubectl apply  -f redis.yaml
#   kubectl get deploy redis
#   kubectl get svc redis
#
# Rollout / 이미지 교체 재배포:
#   # 최신 이미지로 강제 롤링 업데이트
#   kubectl rollout restart deploy/redis
#   kubectl rollout status deploy/redis
#   # 필요 시 롤백
#   kubectl rollout undo deploy/redis

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent
          args: ["--appendonly", "yes"]
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: redic-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  type: NodePort
  selector:
    app: redis
  ports:
    - name: redis
      port: 6379
      targetPort: 6379
      nodePort: 30101


