server:
  port: 90

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    redis:
      host: redis
      port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.fileservice.model

logging:
  level:
    com.example.fileservice: INFO
    org.mybatis: INFO
    org.apache.ibatis: INFO
    com.p6spy: INFO

p6spy:
  logging: sysout
  multiline: true
  sql-format: true

minio:
  endpoint: ${MINIO_ENDPOINT}
  accessKey: ${MINIO_ACCESS_KEY}
  secretKey: ${MINIO_SECRET_KEY}
  bucket:
    images: ${MINIO_BUCKET_IMAGES:images}
    videos: ${MINIO_BUCKET_VIDEOS:videos}

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

file:
  service:
    base-url: ${FILE_SERVICE_BASE_URL}

user:
  service:
    base-url: ${USER_SERVICE_BASE_URL}

# OpenFeign global timeout settings (milliseconds)
feign:
  client:
    config:
      default:
        connectTimeout: 10000   # 10s
        readTimeout: 120000     # 120s for large uploads/downloads
        loggerLevel: BASIC
