server:
  port: 91

spring:
  application:
    name: file-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    redis:
      host: 127.0.0.1
      port: 30101
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:31004/filedb
    username: postgres
    password: postgres
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.fileservice.model

logging:
  level:
    com.example.fileservice: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.p6spy: DEBUG

p6spy:
  logging: sysout
  multiline: true
  sql-format: true

minio:
  endpoint: http://127.0.0.1:30103
  publicEndpoint: http://127.0.0.1:30103
  accessKey: minioadmin
  secretKey: minioadmin123!
  bucket:
    images: images
    videos: videos

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info

