server:
  port: 92
  servlet:
    session:
      cookie:
        same-site: Lax
        secure: false

spring:
  application:
    name: posting-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  data:
    redis:
      host: localhost
      port: 30101
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:31002/postingdb
    username: postgres
    password: postgres
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.postingservice.model



logging:
  level:
    com.example.postingservice: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.p6spy: DEBUG

p6spy:
  logging: sysout
  multiline: true
  sql-format: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info


file:
  service:
    base-url: http://localhost:91

user:
  service:
    base-url: http://localhost:90

# OpenFeign global timeout settings (milliseconds)
feign:
  client:
    config:
      default:
        connectTimeout: 10000   # 10s
        readTimeout: 120000     # 120s for large uploads/downloads
        loggerLevel: BASIC

