server:
  port: 93
  servlet:
    session:
      cookie:
        same-site: Lax
        secure: false

spring:
  application:
    name: notification-service
  cloud:
    openfeign:
      observations:
        enabled: true
  data:
    redis:
      host: localhost
      port: 30101
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:31005/notificationdb
    username: postgres
    password: postgres
  sql:
    init:
      mode: never

mybatis:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.notificationservice.model



logging:
  level:
    com.example.notificationservice: DEBUG
    org.mybatis: DEBUG
    org.apache.ibatis: DEBUG
    com.p6spy: DEBUG

p6spy:
  logging: sysout
  multiline: true
  sql-format: true

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, prometheus
  endpoint:
    prometheus:
      access: read_only
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    propagation:
      type: w3c
  otlp:
    tracing:
      endpoint: http://127.0.0.1:30108/v1/traces  # 추적 데이터 보낼 곳 (Tempo or Jaeger)
    sampling:
      probability: 1.0


file:
  service:
    base-url: http://localhost:91

user:
  service:
    base-url: http://localhost:90

# OpenFeign global timeout settings (milliseconds)
feign:
  client:
    config:
      default:
        connectTimeout: 10000   # 10s
        readTimeout: 120000     # 120s for large uploads/downloads
        loggerLevel: BASIC

